[core]
log_file = "/var/tmp/revad/app.log"
max_cpus = 32

[grpc]
network = "tcp"
address = "0.0.0.0:9999"
access_log = "/var/log/revad/grpc-access.log"
tls_enabled = true
tls_cert = "/etc/gridsecurity/host.cert"
tls_key = "/etc/gridsecurity/host.key"
enabled_services = ["storage_provider_svc", "auth_svc"]

[http]
enabled_services = ["prometheus_svc", "webui_svc"]
network = "tcp"
address = "0.0.0.0:9998"

[grpc.storage_provider_svc]
driver = "local"

[grpc.auth_svc.auth_manager]
driver = "demo"

[grpc.auth_svc.token_manager]
driver = "jwt"

[grpc.auth_svc.user_manager]
driver = "demo"

[grpc.storage_provider_svc.eos]
mgm = "root://nowhere.org"
root_uid = 0
root_gid = 0

[grpc.storage_provider_svc.local]
root = "/tmp"

[http.prometheus_svc]
path = /metrics

[http.webui_svc]
path = /ui

[http.webdav_svc]
path = /webdav
